# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Jars

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
          VERSION_CLS: ci

      - uses: actions/upload-artifact@v3
        with:
          name: Enderbundle-jar
          path: build/libs/*.jar
